#!/usr/bin/env python3

import os
import subprocess
import sys

clang_version = 4.0

clang_bin = "/usr/bin/clang++-" + str(clang_version)

here = os.path.abspath(os.path.dirname(sys.argv[0]))
output = os.path.join(here, ".ycm_extra_conf.py")

flags = []

subprocess.call( \
        clang_bin + " -E -x c++ -v - < /dev/null >/dev/null 2>" + output,
        shell = True)
        
fp = open(output, 'r')
inc = False
for l in fp.readlines():
    l = l.strip()
    if inc:
        if l.startswith("End"):
            break
        else:
            flags.extend(["-isystem", l])
    elif l.startswith("#include <"):
        inc = True
fp.close()

os.unlink(output)
subprocess.call("/usr/bin/pkg-config --cflags " +
        "glibmm-2.4 gthread-2.0 gobject-2.0>=2.44 " +
        "gudev-1.0 " +
        "> " + output,
        shell = True)
fp = open(output, 'r')
flags.extend(fp.read().strip().split())
fp.close()

flags.append("-I" + os.path.join(here, "src"))
flags.append("-I.")
flags.extend(["-Wall", "-Wextra", "-std=c++11", "-xc++"])

os.unlink(output)
fp = open(output, 'w')
fp.write( \
"""def FlagsForFile(filename, **Kwargs):
    return {
        "flags": """ + str(flags) + """,
        "do_cache": True
    }
""")
fp.close()
